// ---------------------------------------------------------------------------
// Protocol catalog used for automatic protocol matching from intake answers.
// Only clinically-actionable protocols are included (surgical document
// templates "Modelos UroDocx" are intentionally excluded from matching).
// ---------------------------------------------------------------------------

export type ProtocolCatalogEntry = {
  id: string;
  title: string;
  category: string;
  keywords: string[];
};

export const PROTOCOL_CATALOG: ProtocolCatalogEntry[] = [
  {
    id: "litiase_renal_ureteral",
    title: "Litíase Renal e Ureteral — Diagnóstico e Tratamento",
    category: "Urologia Geral",
    keywords: [
      "calculose renal",
      "calculo no rim",
      "calculo ureteral",
      "colica nefréetica",
      "pedra no rim",
      "urolitiase",
      "colica renal",
      "litotripsia",
      "leoc",
      "ureteroscopia",
      "ursl",
      "nlpc percutanea",
      "calculo na urina",
      "pedra no ureter",
      "hematuria e dor lombar",
      "dor lombar intensa subitânea",
      "obstrucao ureteral",
      "hidronefrose",
    ],
  },
  {
    id: "itu_masculina_prostatite_aguda",
    title: "ITU Masculina e Prostatite Aguda Bacteriana",
    category: "Urologia Geral",
    keywords: [
      "prostatite aguda",
      "infeccao na prostata",
      "febre e dor ao urinar",
      "itu masculina",
      "infeccao urinaria no homem",
      "prostatite bacteriana",
      "prostatite tipo 1",
      "abscesso prostatico",
      "calafrio e disuria",
      "bactéria na urina homem",
      "retencao urinaria aguda por infeccao",
      "psa elevado por infeccao",
      "ciprofloxacina prostatite",
      "antibiotico prostata",
    ],
  },
  // ─── ANDROLOGIA ──────────────────────────────────────────────────────────
  {
    id: "4_disfuncao_eretil",
    title: "Disfunção Erétil - Abordagem Escalonada",
    category: "Andrologia",
    keywords: [
      "disfuncao eretil",
      "erecao",
      "impotencia",
      "rigidez",
      "manter erecao",
      "perda de erecao",
      "dificuldade de erecao",
      "tadalafila",
      "sildenafila",
      "viagra",
      "cialis",
    ],
  },
  {
    id: "15_ejaculacao_precoce",
    title: "Ejaculação Precoce - Abordagem Multimodal",
    category: "Andrologia",
    keywords: [
      "ejaculacao precoce",
      "ejaculo rapido",
      "gozo rapido",
      "controle da ejaculacao",
      "tempo curto",
      "precoce",
    ],
  },
  {
    id: "16_ejaculacao_retardada",
    title: "Ejaculação Retardada, Anejaculação e Anorgasmia",
    category: "Andrologia",
    keywords: [
      "ejaculacao retardada",
      "demora para ejacular",
      "nao consigo ejacular",
      "anorgasmia",
      "ausencia de orgasmo",
      "nao chego ao orgasmo",
      "nao goza",
      "orgasmo dificil",
      "anejaculacao",
      "dificuldade de ejacular",
    ],
  },
  {
    id: "3_doenca_peyronie",
    title: "Doença de Peyronie - Abordagem Completa",
    category: "Andrologia",
    keywords: [
      "peyronie",
      "curvatura",
      "penis torto",
      "placa peniana",
      "tortuosidade",
      "encurvamento",
      "dor na erecao",
    ],
  },
  {
    id: "24_medicina_sexual_casal",
    title: "Medicina Sexual do Casal - Abordagem Integrada",
    category: "Andrologia",
    keywords: [
      "libido",
      "desejo sexual",
      "relacionamento",
      "casal",
      "frequencia sexual",
      "satisfacao sexual",
    ],
  },
  {
    id: "20_reabilitacao_peniana_pos_prostatectomia",
    title: "Reabilitação Peniana Pós-Prostatectomia Radical",
    category: "Andrologia",
    keywords: [
      "prostatectomia",
      "retirei a prostata",
      "cirurgia de prostata",
      "pos prostatectomia",
      "reabilitacao peniana",
      "cancer de prostata operado",
    ],
  },
  {
    id: "1_implante_protese_peniana",
    title: "Implante de Prótese Peniana Inflável",
    category: "Andrologia",
    keywords: [
      "protese peniana",
      "implante peniano",
      "protese inflavel",
      "implante de penis",
      "cirurgia para erecao",
      "prótese para impotencia",
      "disfuncao eretil grave",
      "falha de tadalafila",
    ],
  },
  {
    id: "1b_protese_semirrigida",
    title: "Prótese Peniana Semirígida",
    category: "Andrologia",
    keywords: [
      "protese semirrigida",
      "implante rigido",
      "protese malleable",
      "protese maleavel",
      "peniana semirigida",
    ],
  },
  {
    id: "prostatite_cronica_sdcp",
    title: "Prostatite Crônica / Síndrome de Dor Crônica Pélvica (SDCP)",
    category: "Andrologia",
    keywords: [
      "prostatite",
      "dor pelvica",
      "dor no perineu",
      "dor entre as pernas",
      "dor na virilha",
      "dor escrotal cronica",
      "prostatite cronica",
      "sdcp",
      "dor ao ejacular",
      "ardencia ao ejacular",
      "dor pos ejaculacao",
      "dor nos testiculos",
      "sensacao de peso na pelve",
    ],
  },
  {
    id: "ginecomastia_masculina",
    title: "Ginecomastia Masculina - Diagnóstico e Tratamento",
    category: "Andrologia",
    keywords: [
      "ginecomastia",
      "seio masculino",
      "mama masculina",
      "peito crescendo",
      "crescimento mamario",
      "glandula mamaria",
      "sensibilidade no peito",
    ],
  },
  {
    id: "epididimite_orquite",
    title: "Epididimite e Orquite - Diagnóstico e Tratamento",
    category: "Andrologia",
    keywords: [
      "epididimite",
      "inflamacao no testiculo",
      "orquite",
      "testiculo inchado",
      "dor no testiculo com febre",
      "testiculo aumentado",
      "epidídimo",
    ],
  },
  {
    id: "kallmann_hhg_congenito",
    title: "Síndrome de Kallmann e Hipogonadismo Hipogonadotrófico Congênito",
    category: "Andrologia",
    keywords: [
      "sindrome de kallmann",
      "anosmia e ausencia de puberdade",
      "hipogonadismo hipogonadotrofico",
      "puberdade ausente",
      "hhg congenito",
      "lh fsh baixos com testosterona baixa",
      "ausencia de puberdade masculina",
      "testosterona baixa jovem",
      "hcg para fertilidade",
      "gonal-f infertilidade hipogonadismo",
      "infertilidade por hhg",
      "micropenis congenito",
      "criptorquidia e infertilidade",
      "gonadotrofinas para espermatogenese",
    ],
  },
  // ─── HORMÔNIOS & PERFORMANCE ──────────────────────────────────────────────
  {
    id: "8_trt_performance",
    title: "TRT e Otimização Hormonal Masculina",
    category: "Hormônios & Performance",
    keywords: [
      "testosterona baixa",
      "reposicao hormonal",
      "trt",
      "cansaco",
      "fadiga",
      "disposicao",
      "hipogonadismo",
      "perda de massa muscular",
      "humor",
      "energia baixa",
    ],
  },
  {
    id: "22_checkup_performance",
    title: "Check-up de Performance e Longevidade Masculina",
    category: "Hormônios & Performance",
    keywords: [
      "checkup",
      "check-up",
      "longevidade",
      "performance",
      "prevencao",
      "exames de rotina",
      "qualidade de vida",
    ],
  },
  {
    id: "9_trt_estetico_danos",
    title: "Manejo de Danos por Esteroides Anabolizantes",
    category: "Hormônios & Performance",
    keywords: [
      "anabolizante",
      "esteroide",
      "ciclo",
      "academia",
      "bombei",
      "hormonio para academia",
    ],
  },
  {
    id: "10_terapia_pos_ciclo",
    title: "Terapia Pós-Ciclo (TPC) Baseada em Evidências",
    category: "Hormônios & Performance",
    keywords: ["pos ciclo", "tpc", "parar ciclo", "recuperar testiculo"],
  },
  {
    id: "25_homem_trans",
    title: "Saúde Hormonal do Homem Trans",
    category: "Hormônios & Performance",
    keywords: [
      "homem trans",
      "trans",
      "ftm",
      "transexual masculino",
      "hormonioterapia trans",
      "testosterona para trans",
      "masculinizacao",
    ],
  },
  // ─── INFERTILIDADE & MICROCIRURGIA ────────────────────────────────────────
  {
    id: "14_infertilidade_masculina",
    title: "Investigação e Manejo da Infertilidade Masculina",
    category: "Infertilidade & Microcirurgia",
    keywords: [
      "infertilidade",
      "nao consigo engravidar",
      "tentando engravidar",
      "dificuldade para ter filho",
      "espermograma",
      "azoospermia",
      "oligospermia",
      "fertilidade",
    ],
  },
  {
    id: "2_varicocelectomia",
    title: "Varicocelectomia Subinguinal Microcirúrgica",
    category: "Infertilidade & Microcirurgia",
    keywords: ["varicocele", "veia dilatada no testiculo", "varizes no testiculo"],
  },
  {
    id: "5b_reversao_vasectomia",
    title: "Reversão de Vasectomia Microcirúrgica",
    category: "Infertilidade & Microcirurgia",
    keywords: [
      "reversao de vasectomia",
      "reverter vasectomia",
      "voltar a ter filhos",
      "desfazer vasectomia",
    ],
  },
  {
    id: "19_preservacao_fertilidade_oncologica",
    title: "Preservação de Fertilidade Oncológica Masculina",
    category: "Infertilidade & Microcirurgia",
    keywords: [
      "congelar esperma",
      "preservar fertilidade",
      "quimioterapia",
      "cancer e fertilidade",
      "criopreservacao",
    ],
  },
  {
    id: "5_micro_tese",
    title: "Micro-TESE - Extração Microcirúrgica de Espermatozoides",
    category: "Infertilidade & Microcirurgia",
    keywords: [
      "azoospermia",
      "micro tese",
      "sem espermatozoide",
      "nao tem esperma no ejaculado",
      "extracao de espermatozoide",
      "tese",
      "pesa",
      "recuperacao de esperma",
    ],
  },
  {
    id: "espermograma_fertilidade",
    title: "Interpretação do Espermograma e Conduta",
    category: "Infertilidade & Microcirurgia",
    keywords: [
      "espermograma",
      "qualidade do esperma",
      "morfologia do esperma",
      "motilidade",
      "oligozoospermia",
      "astenospermia",
      "astenozoospermia",
      "teratospermia",
      "resultado do espermograma",
    ],
  },
  // ─── PROCEDIMENTOS DE CONSULTÓRIO ─────────────────────────────────────────
  {
    id: "6_vasectomia_sem_bisturi",
    title: "Vasectomia Sem Bisturi",
    category: "Procedimentos de Consultório",
    keywords: [
      "vasectomia",
      "nao quero mais filhos",
      "esterilizacao",
      "contracepcao definitiva",
    ],
  },
  {
    id: "21_li_eswt_ondas_choque",
    title: "Terapia por Ondas de Choque Extracorpóreas (Li-ESWT)",
    category: "Procedimentos de Consultório",
    keywords: ["ondas de choque", "li-eswt", "eswt", "ondas de choque peniana"],
  },
  {
    id: "7_engrossamento_peniano_ha",
    title: "Engrossamento Peniano com Ácido Hialurônico",
    category: "Procedimentos de Consultório",
    keywords: [
      "engrossamento peniano",
      "grossura do penis",
      "acido hialuronico no penis",
      "calibre do penis",
      "espessura peniana",
      "aumento do penis",
    ],
  },
  {
    id: "11_circuncisao_frenuloplastia",
    title: "Circuncisão e Frenuloplastia",
    category: "Procedimentos de Consultório",
    keywords: [
      "circuncisao",
      "postectomia",
      "fimose",
      "prepucio",
      "frenuloplastia",
      "frenulo curto",
      "dor durante relacao",
    ],
  },
  {
    id: "12_lipo_suprapubica_webbing",
    title: "Lipoaspiração Suprapúbica e Correção de Webbing Peniano",
    category: "Procedimentos de Consultório",
    keywords: [
      "gordura suprapubica",
      "penis enterrado",
      "webbing peniano",
      "lipo suprapubica",
      "penis escondido",
      "gordura no penis",
    ],
  },
  {
    id: "23_prp_intracavernoso",
    title: "PRP Intracavernoso (Plasma Rico em Plaquetas)",
    category: "Procedimentos de Consultório",
    keywords: [
      "prp",
      "plasma rico em plaquetas",
      "injecao no penis",
      "tratamento regenerativo",
      "platelet rich plasma",
      "prp peniano",
    ],
  },
  // ─── UROLOGIA GERAL ───────────────────────────────────────────────────────
  {
    id: "13_hpb_manejo_completo",
    title: "Hiperplasia Prostática Benigna (HPB) - Manejo Clínico e Cirúrgico",
    category: "Urologia Geral",
    keywords: [
      "jato fraco",
      "levanto a noite para urinar",
      "noctúria",
      "nocturia",
      "esvaziamento",
      "prostata aumentada",
      "hiperplasia",
      "hpb",
      "dificuldade para urinar",
      "urgencia urinaria",
      "gotejamento",
    ],
  },
  {
    id: "29_itu_repeticao",
    title: "Infecção do Trato Urinário (ITU) de Repetição no Homem",
    category: "Urologia Geral",
    keywords: [
      "infeccao urinaria",
      "itu",
      "ardencia para urinar",
      "cistite",
      "infeccao de repeticao",
    ],
  },
  {
    id: "27_litiase_renal",
    title: "Litíase Renal Masculina e Feminina",
    category: "Urologia Geral",
    keywords: ["pedra no rim", "calculo renal", "litiase", "colica renal"],
  },
  {
    id: "28_incontinencia_urinaria",
    title: "Incontinência Urinária Masculina e Feminina",
    category: "Urologia Geral",
    keywords: [
      "perco urina",
      "incontinencia",
      "escapa urina",
      "perda de urina",
      "uso de fralda",
    ],
  },
  {
    id: "18_dor_escrotal_cronica",
    title: "Dor Escrotal Crônica - Investigação e Manejo",
    category: "Urologia Geral",
    keywords: ["dor no testiculo", "dor escrotal", "dor na bolsa", "orquialgia"],
  },
  // ─── UROLOGIA GERAL ──────────────────────────────────────────────────────
  {
    id: "cancer_testicular",
    title: "Câncer de Testículo - Estadiamento, Workup e Seguimento",
    category: "Urologia Geral",
    keywords: [
      "cancer de testiculo",
      "tumor testicular",
      "massa no testiculo",
      "nodulo testicular",
      "seminoma",
      "nsgct",
      "igcccg",
      "orquiectomia",
      "bep quimioterapia",
      "marcadores tumorais testiculo",
      "afp beta hcg testiculo",
      "estadiamento testicular",
    ],
  },
  {
    id: "estenose_uretral",
    title: "Estenose Uretral Masculina - Diagnóstico e Tratamento",
    category: "Urologia Geral",
    keywords: [
      "estenose uretral",
      "estreitamento da uretra",
      "jato fraco",
      "uretroplastia",
      "uretrotomia",
      "rug uretrografia",
      "estenose de uretra",
      "calibre do jato",
      "obstrucao uretral",
      "sachse",
      "buccal mucosa graft",
      "enxerto mucosa oral",
    ],
  },
  // ─── ANDROLOGIA ──────────────────────────────────────────────────────────
  {
    id: "liquen_escleroso_peniano",
    title: "Líquen Escleroso Peniano (BXO) - Diagnóstico e Tratamento",
    category: "Andrologia",
    keywords: [
      "liquen escleroso",
      "bxo",
      "balanite xerótica obliterante",
      "mancha branca no penis",
      "branqueamento penis",
      "placa branca glande",
      "prepucio endurecido",
      "fimose adquirida",
      "clobetasol penis",
      "biopsia glande",
      "lesao branca penis",
      "liquen",
    ],
  },
  // ─── INFERTILIDADE & MICROCIRURGIA ──────────────────────────────────────
  {
    id: "varicocele",
    title: "Varicocele - Diagnóstico, Indicações e Tratamento",
    category: "Infertilidade & Microcirurgia",
    keywords: [
      "varicocele",
      "varizes testiculares",
      "dor escrotal",
      "peso no testiculo",
      "varicose testiculo",
      "varicocelectomia",
      "operacao varicocele",
      "varicocele e fertilidade",
      "varizes no escroto",
      "doppler escrotal varicocele",
    ],
  },
  {
    id: "azoospermia_hipospermia",
    title: "Azoospermia e Hipospermia - Workup Diagnóstico",
    category: "Infertilidade & Microcirurgia",
    keywords: [
      "azoospermia",
      "nao tem espermatozoide",
      "esperma zerado",
      "hipospermia",
      "pouco semen",
      "semen com volume baixo",
      "micro tese indicacao",
      "noa obstrutiva",
      "oa azoospermia",
      "klinefelter infertilidade",
      "cbavd ausencia deferente",
      "ejaculacao retrograda investigacao",
      "fragmentacao dna espermático",
    ],
  },
  {
    id: "dfi_fragmentacao_dna",
    title: "Fragmentação de DNA Espermático (DFI) — Diagnóstico e Manejo",
    category: "Infertilidade & Microcirurgia",
    keywords: [
      "fragmentacao dna espermático",
      "dfi alto",
      "dfi espermático",
      "dna do espermatozoide danificado",
      "aborto de repeticao masculino",
      "falha de fiv repetida",
      "halosperm",
      "scsa sperm chromatin",
      "tunel sperm",
      "dna oxidado espermatozoide",
      "antioxidante para espermatozoide",
      "qualidade do dna espermático",
      "icsi testicular dfi",
      "macs selecao espermatozoide",
    ],
  },
  // ─── URGÊNCIAS UROLÓGICAS ─────────────────────────────────────────────────
  {
    id: "fratura_peniana",
    title: "Fratura Peniana e Trauma Genital Agudo - Protocolo de Urgência",
    category: "Urgências Urológicas",
    keywords: [
      "fratura peniana",
      "quebrou o penis",
      "barulho no penis durante sexo",
      "penis roxo após sexo",
      "hematoma peniano",
      "trauma genital",
      "penis inclinado após sexo",
      "ruptura tunica albugínea",
      "eggplant deformity",
      "trauma escrotal",
      "ruptura testicular",
      "amputação peniana",
    ],
  },
  {
    id: "17_priapismo_emergencia",
    title: "Priapismo - Protocolo de Emergência",
    category: "Urgências Urológicas",
    keywords: ["priapismo", "erecao que nao baixa", "erecao prolongada"],
  },
  {
    id: "torcao_testicular",
    title: "Torção Testicular - Protocolo de Urgência",
    category: "Urgências Urológicas",
    keywords: [
      "torcao testicular",
      "dor testiculo repentina",
      "testiculo doendo muito",
      "dor aguda no testiculo",
      "testiculo subiu",
      "emergencia testicular",
    ],
  },
  // ─── UROLOGIA FEMININA ────────────────────────────────────────────────────
  {
    id: "botox_intravesical",
    title: "Toxina Botulínica Intravesical - Bexiga Hiperativa",
    category: "Urologia Feminina",
    keywords: [
      "botox na bexiga",
      "botox intravesical",
      "bexiga hiperativa",
      "urgencia incontrolavel",
      "bexiga hiperreativa",
      "overactive bladder",
      "incontinencia de urgencia",
    ],
  },
  {
    id: "iue_feminina",
    title: "Incontinência Urinária de Esforço Feminina (IUE)",
    category: "Urologia Feminina",
    keywords: [
      "incontinencia urinaria de esforco",
      "perde urina ao tossir",
      "perde xixi ao pular",
      "sling suburetral",
      "tvt incontinencia",
      "tot incontinencia",
      "fisioterapia assoalho pelvico incontinencia",
      "iue feminina",
      "perda involuntaria de urina",
      "incontinencia ao espirrar",
      "sling para bexiga",
      "hipermobilidade uretral",
      "deficiencia intrinseca esfíncter",
      "duloxetina incontinencia",
      "kegel bexiga",
      "perda urina exercicio",
    ],
  },
];

export function getProtocolById(id: string): ProtocolCatalogEntry | undefined {
  return PROTOCOL_CATALOG.find((p) => p.id === id);
}